name: Update Metro Data

on:
  workflow_dispatch: # 允许手动点击按钮运行
  workflow_call: # 声明这是可以被调用的
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出你的代码，否则虚拟机里没脚本文件
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main             # 强制指定拉取最新的 main 分支
          fetch-depth: 0        # 获取完整历史
          token: ${{ secrets.MY_TOKEN }}

      # 第二步：安装 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 指定你需要的版本

      # 第三步：安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install questionary
          pip install pyjson5
          pip install pypinyin
          pip install tabulate
          pip install tqdm
          pip install pillow

      - name: Run script
        run: python generate_data.py

      - name: Commit and Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data.js
          git commit -m "Auto-data-update: 自动更新地铁数据 data.js"
          git push
